baseURL = 'https://blog.gereader.xyz'
languageCode = 'en-us'
title = "blog.gereader.xyz"
theme = "hugo-blog-awesome"

[params]
  goToTop = true
  defaultColor = "auto"  # or "light" or "dark"
  description = "My technical blog to showcase projects as I build them"
  renderAnchorLinks = true

[params.author]
  avatar = "images/MyFace.jpeg"
  intro = "Things I Broke, Things I Fixed â€” by Gene Reader"
  name = "Gene Reader"
  description = "Platform engineer focused on automation and reliability. I write about the things that broke, the things I fixed, and the mistakes I want to avoid repeating."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/gereader"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/GeReader"

[services.disqus]
  shortname = "blog-gereader-xyz"

[frontmatter]
  format = "yaml"

[params.seo]
  title = "Gene's Blog"
  description = "Blog about DevOps, CICD, AWS, OCI, anything cloud and other tech insights"


[markup]
  [markup.goldmark.parser]
    autoHeadingID = true